### ISSUE TITLE
yt-dlp + ffmpeg update check skipped 

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-packaging#35]
![image](https://user-images.githubusercontent.com/13978119/199102361-a3fbcc9e-beee-431d-8282-17382cde97cc.png)

Now it doesn't check for yt-dlp updates (not even rss feed) + doesn't check for ffmpeg updates.

So if yt-dlp exists = don't update it? what's the reason behind it? I want to update mpv + yt-dlp + ffmpeg.

https://github.com/shinchiro/mpv-packaging/pull/33

**Comment by Hill-98** [comment]
Well, it looks like you added the mpv path to the PATH environment variable, I didn't take that into account, I'll fix it when I wake up.

**Comment by Bec-de-Xorbin** [comment]
> Well, it looks like you added the mpv path to the PATH environment variable, I didn't take that into account, I'll fix it when I wake up.

Hmm, so this should be fixed now? If I have mpv path in PATH the situation is exactly the same as in OP screenshot.

**Comment by Hill-98** [comment]
@Bec-de-Xorbin #36 has fixed this, just need @shinchiro to merge it.

**Comment by mortyobnoxious** [comment]
I still get the this: 

![x8CB4HwqYs](https://user-images.githubusercontent.com/42044258/215523661-0b3f9670-4be6-41ee-9dc1-be99b24d94d6.png)

**Comment by mortyobnoxious** [comment]
I still get this, I delete this line after everyupdate:
```
    if (Check-Ytplugin-In-System) {
        Write-Host "yt-dlp.exe or youtube-dl.exe already exists in your system, skip the update check." -ForegroundColor Green
        return
    }
```
